// Code generated by github.com/nofun97/adobo, DO NOT EDIT.

package schema

// testdata
type JustComp struct {
    Age *interface{} `json:"age,omitempty" yaml:"age,omitempty"`
    Blank *interface{} `json:"blank,omitempty" yaml:"blank,omitempty"`
    Data *interface{} `json:"data,omitempty" yaml:"data,omitempty"`
    Name *interface{} `json:"name,omitempty" yaml:"name,omitempty"`
    Referenced *JustCompDefsAnimal `json:"referenced,omitempty" yaml:"referenced,omitempty"`
}

type JustCompDefsAnimalOpt0 *JustCompDefsAnimal

type JustCompDefsAnimalOpt1 string

type JustCompDefsAnimalOpt2 struct {
    Vertebrate *string `json:"vertebrate,omitempty" yaml:"vertebrate,omitempty"`
}

type JustCompDefsAnimalOpt3 struct {
    Invertebrate *string `json:"invertebrate,omitempty" yaml:"invertebrate,omitempty"`
}

type JustCompOpt0 float

type JustCompOpt0 string

type JustCompOpt1 float

type JustCompOpt2 struct {
    Animal *string `json:"animal,omitempty" yaml:"animal,omitempty"`
    Vegetable *string `json:"vegetable,omitempty" yaml:"vegetable,omitempty"`
}